# Generated by Django 5.0.3 on 2024-04-06 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='username')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('nombres', models.CharField(blank=True, default='', max_length=35, verbose_name='Nombre(s)')),
                ('apellido_paterno', models.CharField(blank=True, default='', max_length=25, verbose_name='Apellido Paterno')),
                ('apellido_materno', models.CharField(blank=True, default='', max_length=25, verbose_name='Apellido Materno')),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], default='', max_length=1, verbose_name='Género')),
                ('nombre_calle', models.CharField(blank=True, default='', max_length=100, verbose_name='Nombre de calle')),
                ('numero_calle', models.CharField(blank=True, default='', max_length=10, verbose_name='Número de calle')),
                ('municipio', models.CharField(blank=True, default='', max_length=100, verbose_name='Municipio')),
                ('estado', models.CharField(blank=True, default='', max_length=100, verbose_name='Estado')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
