# Generated by Django 5.0.3 on 2024-04-06 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paciente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='username',
            field=models.CharField(max_length=150, unique=True, verbose_name='CURP'),
        ),
    ]
