# Generated by Django 5.0.3 on 2024-04-06 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paciente', '0003_alter_paciente_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='username',
            field=models.CharField(max_length=18, unique=True, verbose_name='CURP'),
        ),
    ]
